import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it, vi } from "vitest";
import { PlanInbox } from "../src/plans/inbox.js";
import { cleanup, isolateStateDir, makeTmpDir, write } from "./helpers.js";


function sha256Hex(value: Buffer | string): string {
  return createHash("sha256").update(value).digest("hex");
}

function canonicalJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
  if (value !== null && typeof value === "object") {
    return `{${Object.entries(value as Record<string, unknown>)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, item]) => `${JSON.stringify(key)}:${canonicalJson(item)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function stagedProject(root: string, project = "sample-project"): { digest: string; project: string } {
  const data = "# Sample\n";
  write(root, `${project}/PROJECT.md`, data);
  const files = [{ path: "PROJECT.md", bytes: Buffer.byteLength(data), sha256: sha256Hex(data) }];
  const payload = {
    schema: 2,
    project,
    classification: "synthetic",
    files,
    limits: { max_file_bytes: 1_000_000, max_total_bytes: 10_000_000 },
  };
  const digest = sha256Hex(canonicalJson(payload) + "\n");
  write(root, `${project}/CONTEXT-MANIFEST.json`, JSON.stringify({ ...payload, approval_digest: digest }));
  fs.chmodSync(root, 0o700);
  fs.chmodSync(path.join(root, project), 0o700);
  return { digest, project };
}

function stagedProjectWithFile(root: string, relative: string, data = "safe text\n"): { digest: string; project: string } {
  const project = "policy-project";
  write(root, `${project}/${relative}`, data);
  const payload = {
    schema: 2,
    project,
    classification: "synthetic",
    files: [{ path: relative, bytes: Buffer.byteLength(data), sha256: sha256Hex(data) }],
    limits: { max_file_bytes: 1_000_000, max_total_bytes: 10_000_000 },
  };
  const digest = sha256Hex(canonicalJson(payload) + "\n");
  write(root, `${project}/CONTEXT-MANIFEST.json`, JSON.stringify({ ...payload, approval_digest: digest }));
  fs.chmodSync(root, 0o700);
  fs.chmodSync(path.join(root, project), 0o700);
  return { digest, project };
}

const PLAN = `FILES_USED:\n- PROJECT.md\n\nASSUMPTIONS:\n- None\n\nPLAN:\n- Make the safe change.\n\nOPEN_QUESTIONS:\n- None\n`;
const FIXTURE = path.join(path.dirname(fileURLToPath(import.meta.url)), "fixtures", "manifest-v2-golden");

describe("PlanInbox", () => {
  it("accepts the manifest-v2 golden fixture generated by the C2C staging producer", () => {
    isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace-golden");
    try {
      const project = "manifest-v2-golden";
      fs.cpSync(FIXTURE, path.join(workspaceRoot, project), { recursive: true });
      fs.chmodSync(workspaceRoot, 0o700);
      fs.chmodSync(path.join(workspaceRoot, project), 0o700);
      const inbox = new PlanInbox({ workspaceRoot, workspaceId: "golden" });
      const authorization = inbox.authorize({
        project,
        digest: "50cf047d1b8563455f24d4dfa26a39a9e5c702fc1cba9ff3a92253c5c2b580f7",
      });
      expect(authorization.token).toMatch(/^c2c_plan_/);
    } finally {
      cleanup(workspaceRoot);
    }
  });

  it("accepts one authorized plan into an owner-only inbox outside the workspace", () => {
    const stateDir = isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace");
    try {
      const binding = stagedProject(workspaceRoot);
      const inbox = new PlanInbox({ workspaceRoot, workspaceId: "workspace123" });
      const authorization = inbox.authorize({ ...binding, ttlMs: 60_000 });

      const receipt = inbox.submit({ ...binding, authorization: authorization.token, content: PLAN });

      expect(receipt.sha256).toBe(sha256Hex(PLAN));
      expect(receipt.bytes).toBe(Buffer.byteLength(PLAN));
      expect(receipt.path.startsWith("plan-inbox:/workspace123/sample-project/")).toBe(true);
      const savedFile = path.join(stateDir, ...receipt.path.replace("plan-inbox:/", "plan-inbox/").split("/"));
      expect(savedFile.startsWith(workspaceRoot)).toBe(false);
      expect(fs.readFileSync(savedFile, "utf8")).toBe(PLAN);
      expect(fs.statSync(savedFile).mode & 0o777).toBe(0o600);
      expect(fs.statSync(path.dirname(savedFile)).mode & 0o077).toBe(0);
      expect(() => inbox.submit({ ...binding, authorization: authorization.token, content: PLAN })).toThrow(
        /authorization/i
      );
    } finally {
      cleanup(workspaceRoot);
    }
  });

  it("rejects changed staged data and consumes the authorization", () => {
    isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace-changed");
    try {
      const binding = stagedProject(workspaceRoot);
      const inbox = new PlanInbox({ workspaceRoot, workspaceId: "workspace-changed" });
      const authorization = inbox.authorize({ ...binding });
      write(workspaceRoot, `${binding.project}/PROJECT.md`, "changed after approval\n");

      expect(() => inbox.submit({ ...binding, authorization: authorization.token, content: PLAN })).toThrow(
        /staged file/i
      );
      expect(() => inbox.submit({ ...binding, authorization: authorization.token, content: PLAN })).toThrow(
        /authorization/i
      );
    } finally {
      cleanup(workspaceRoot);
    }
  });

  it("rejects unapproved FILES_USED paths and does not create an inbox file", () => {
    const stateDir = isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace-files");
    try {
      const binding = stagedProject(workspaceRoot);
      const inbox = new PlanInbox({ workspaceRoot, workspaceId: "workspace-files" });
      const authorization = inbox.authorize({ ...binding });
      const invalidPlan = PLAN.replace("PROJECT.md", "NOT-APPROVED.md");

      expect(() => inbox.submit({ ...binding, authorization: authorization.token, content: invalidPlan })).toThrow(
        /FILES_USED/i
      );
      expect(fs.existsSync(path.join(stateDir, "plan-inbox", "workspace-files", binding.project))).toBe(false);
    } finally {
      cleanup(workspaceRoot);
    }
  });

  it("rejects paths that the C2C staging policy cannot produce", () => {
    isolateStateDir();
    const roots: string[] = [];
    try {
      const cases = [
        [".env", "safe text\n"],
        ["secrets.json", "safe text\n"],
        ["image.png", "safe text\n"],
        ["PROJECT.md", "api_key=abcdefghijklmno\n"],
      ] as const;
      for (const [index, [relative, data]] of cases.entries()) {
        const workspaceRoot = makeTmpDir(`plan-workspace-policy-${index}`);
        roots.push(workspaceRoot);
        const binding = stagedProjectWithFile(workspaceRoot, relative, data);
        const inbox = new PlanInbox({ workspaceRoot, workspaceId: `policy-${index}` });
        expect(() => inbox.authorize({ ...binding })).toThrow(/manifest|path|secret|sensitive|type/i);
      }
    } finally {
      roots.forEach(cleanup);
    }
  });

  it("rejects content before the first required section", () => {
    isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace-preamble");
    try {
      const binding = stagedProject(workspaceRoot);
      const inbox = new PlanInbox({ workspaceRoot, workspaceId: "preamble" });
      const { token: grant } = inbox.authorize({ ...binding });
      expect(() => inbox.submit({
        ...binding,
        authorization: grant,
        content: `Untrusted preamble\n${PLAN}`,
      })).toThrow(/section|preamble|FILES_USED/i);
    } finally {
      cleanup(workspaceRoot);
    }
  });

  it("rejects traversal, symlinks, extra files, malformed sections, and binding reuse", () => {
    isolateStateDir();
    const roots: string[] = [];
    try {
      const traversalRoot = makeTmpDir("plan-workspace-traversal");
      roots.push(traversalRoot);
      const traversalInbox = new PlanInbox({ workspaceRoot: traversalRoot, workspaceId: "traversal" });
      expect(() => traversalInbox.authorize({ project: "../escape", digest: "0".repeat(64) })).toThrow(/project/i);

      const symlinkRoot = makeTmpDir("plan-workspace-symlink");
      roots.push(symlinkRoot);
      const symlinkBinding = stagedProject(symlinkRoot);
      const stagedFile = path.join(symlinkRoot, symlinkBinding.project, "PROJECT.md");
      fs.rmSync(stagedFile);
      fs.symlinkSync("/etc/hosts", stagedFile);
      const symlinkInbox = new PlanInbox({ workspaceRoot: symlinkRoot, workspaceId: "symlink" });
      expect(() => symlinkInbox.authorize({ ...symlinkBinding })).toThrow(/symlink/i);

      const extraRoot = makeTmpDir("plan-workspace-extra");
      roots.push(extraRoot);
      const extraBinding = stagedProject(extraRoot);
      write(extraRoot, `${extraBinding.project}/EXTRA.md`, "not approved\n");
      const extraInbox = new PlanInbox({ workspaceRoot: extraRoot, workspaceId: "extra" });
      expect(() => extraInbox.authorize({ ...extraBinding })).toThrow(/file set/i);

      const bindingRoot = makeTmpDir("plan-workspace-binding");
      roots.push(bindingRoot);
      const binding = stagedProject(bindingRoot);
      const bindingInbox = new PlanInbox({ workspaceRoot: bindingRoot, workspaceId: "binding" });
      const authorization = bindingInbox.authorize({ ...binding });
      expect(() =>
        bindingInbox.submit({ ...binding, digest: "f".repeat(64), authorization: authorization.token, content: PLAN })
      ).toThrow(/authorization/i);

      const malformedAuthorization = bindingInbox.authorize({ ...binding });
      expect(() =>
        bindingInbox.submit({
          ...binding,
          authorization: malformedAuthorization.token,
          content: PLAN.replace("OPEN_QUESTIONS:", "PLAN:"),
        })
      ).toThrow(/sections/i);
    } finally {
      roots.forEach(cleanup);
    }
  });

  it("rejects symlinked inbox ancestors and duplicate manifest members", () => {
    const stateDir = isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace-inbox-link");
    const duplicateRoot = makeTmpDir("plan-workspace-duplicate");
    try {
      stagedProject(workspaceRoot);
      const linkedInbox = path.join(stateDir, "plan-inbox");
      fs.symlinkSync(workspaceRoot, linkedInbox);
      expect(() => new PlanInbox({ workspaceRoot, workspaceId: "linked" })).toThrow(/inbox|symlink/i);
      fs.rmSync(linkedInbox);

      const binding = stagedProject(duplicateRoot);
      const manifestPath = path.join(duplicateRoot, binding.project, "CONTEXT-MANIFEST.json");
      const original = fs.readFileSync(manifestPath, "utf8");
      fs.writeFileSync(manifestPath, original.replace("{", '{"schema":1,'));
      const inbox = new PlanInbox({ workspaceRoot: duplicateRoot, workspaceId: "duplicate" });
      expect(() => inbox.authorize({ ...binding })).toThrow(/duplicate/i);
    } finally {
      cleanup(workspaceRoot);
      cleanup(duplicateRoot);
    }
  });

  it("rejects an inbox parent replaced with a symlink before creating any child", () => {
    const stateDir = isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace-parent-swap");
    const victimRoot = makeTmpDir("plan-victim");
    try {
      const binding = stagedProject(workspaceRoot);
      const inbox = new PlanInbox({ workspaceRoot, workspaceId: "parent-swap" });
      const authorization = inbox.authorize({ ...binding });
      const workspaceInbox = path.join(stateDir, "plan-inbox", "parent-swap");
      fs.rmSync(workspaceInbox, { recursive: true });
      fs.symlinkSync(victimRoot, workspaceInbox);

      expect(() => inbox.submit({ ...binding, authorization: authorization.token, content: PLAN })).toThrow(/inbox|symlink/i);
      expect(fs.existsSync(path.join(victimRoot, binding.project))).toBe(false);
    } finally {
      cleanup(workspaceRoot);
      cleanup(victimRoot);
    }
  });

  it("rejects a symlink in the configured state-directory ancestry before creating state", () => {
    const workspaceRoot = makeTmpDir("plan-workspace-state-link");
    const stateParent = makeTmpDir("plan-state-parent");
    const victimRoot = makeTmpDir("plan-state-victim");
    const previous = process.env.C2C_STATE_DIR;
    const link = path.join(stateParent, "linked");
    fs.symlinkSync(victimRoot, link);
    process.env.C2C_STATE_DIR = path.join(link, "state");
    try {
      expect(() => new PlanInbox({ workspaceRoot, workspaceId: "state-link" })).toThrow(/symlink|state|inbox/i);
      expect(fs.existsSync(path.join(victimRoot, "state"))).toBe(false);
    } finally {
      if (previous === undefined) delete process.env.C2C_STATE_DIR;
      else process.env.C2C_STATE_DIR = previous;
      cleanup(workspaceRoot);
      cleanup(stateParent);
      cleanup(victimRoot);
    }
  });

  it("refuses a state directory inside the workspace before creating it", () => {
    const workspaceRoot = makeTmpDir("plan-workspace-state-overlap");
    const previous = process.env.C2C_STATE_DIR;
    const unsafeState = path.join(workspaceRoot, ".c2c-state");
    process.env.C2C_STATE_DIR = unsafeState;
    try {
      expect(() => new PlanInbox({ workspaceRoot, workspaceId: "overlap" })).toThrow(/separate|workspace|inbox/i);
      expect(fs.existsSync(unsafeState)).toBe(false);
    } finally {
      if (previous === undefined) delete process.env.C2C_STATE_DIR;
      else process.env.C2C_STATE_DIR = previous;
      cleanup(workspaceRoot);
    }
  });

  it("fails closed for plan writes on platforms without enforced owner-only ACLs", () => {
    isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace-windows");
    try {
      const binding = stagedProject(workspaceRoot);
      const inbox = new PlanInbox({ workspaceRoot, workspaceId: "windows", platform: "win32" });
      expect(() => inbox.authorize({ ...binding })).toThrow(/platform|Windows|ACL/i);
    } finally {
      cleanup(workspaceRoot);
    }
  });

  it("expires an authorization at its exact deadline", () => {
    isolateStateDir();
    const workspaceRoot = makeTmpDir("plan-workspace-expiry");
    vi.useFakeTimers();
    try {
      vi.setSystemTime(new Date("2026-09-05T00:00:00Z"));
      const binding = stagedProject(workspaceRoot);
      const inbox = new PlanInbox({ workspaceRoot, workspaceId: "expiry" });
      const authorization = inbox.authorize({ ...binding, ttlMs: 1_000 });
      vi.setSystemTime(authorization.expiresAt);
      expect(() => inbox.submit({ ...binding, authorization: authorization.token, content: PLAN })).toThrow(/expired/i);
    } finally {
      vi.useRealTimers();
      cleanup(workspaceRoot);
    }
  });
});
